---
title: "Feux agricoles et pastoraux"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Initialization

1.  Setup layout parameters

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

2.  Setup global options

```{r, include=FALSE}
#options(java.parameters = "- Xmx1024m") #Allow to increase memory limit
```

3.  Load required packages

```{r, message=FALSE}
library(tidyverse) # Easily Install and Load the 'Tidyverse'
library(readxl) # Read Excel Files, CRAN v1.3.1 
library(data.table) # Extension of `data.frame`
library(janitor) # Simple Tools for Examining and Cleaning Dirty Data
library(lubridate) # Make Dealing with Dates a Little Easier
library(annotater) # Annotate Package Load Calls, [github::luisDVA/annotater] v0.1.3
library(sf)
library(tmap)
library(leaflet)
library(tmaptools)
```

4.  Get data

```{r}
agri_fire<-read_excel("data/Base-feux-agricoles-pastoraux2001-2021-10092021.xlsx",sheet = 1)
pasto_fire<-read_excel("data/Base-feux-agricoles-pastoraux2001-2021-10092021.xlsx",sheet = 2)
commune_gps<-read_csv2("data/commune_gps_tidied.csv")
```

# Data Cleaning and Tidying

1.  Data Cleaning

-   Agricultural fire data

```{r}
agri_fire<-as_tibble(agri_fire)
agri_fire%>%
  filter(!mois=="")%>%
  select(!rmq&!`...10`)->agri_fire

```

-   Pastoral fire data

```{r}
pasto_fire<-as_tibble(pasto_fire)
pasto_fire%>%
  filter(!mois=="")%>%
  select(!rmq&!`...10`)->pasto_fire
```

2.  Data Tidying

-   Agricultural fire data

```{r}
clean_names(agri_fire)->agri_fire
agri_fire%>%
  rename(code_commune=`x4`)->agri_fire

agri_fire%>%
  slice(c(1:369,371:1396,1398:nrow(agri_fire)))%>%
  na.omit(code_commune)-> agri_fire

agri_fire%>%
  mutate(annee=as.integer(annee),
         mois=as.integer(mois),
         jour=as.integer(jour),
         code_commune=as.character(code_commune),
         commune=as.character(commune),
         surface_ha=as.numeric(surface_ha),
         type_vegetation=as.factor(type_vegetation),
         source=as.factor(source))->agri_fire

# agri_fire%>%
#   filter(surface_ha=="na")%>%
#   count->na1
# test%>%
#   filter(is.na(surface_ha))%>%
#   count->na2
# na1==na2
# 
# seqna1<-which(agri_fire$surface_ha=="na")
# seqna2<-which(is.na(test$surface_ha))
# tabcomp<-cbind(seqna1,seqna2)
# tabcomp<-as_tibble(tabcomp)
# tabcomp%>%
#   mutate(diff=(seqna1-seqna2))->tabcomp
# tabcomp%>%
#   filter(diff!=0)

#370,1397,3225

agri_fire%>% 
  mutate(date = make_datetime(annee, mois, jour))->agri_fire

```

-   Pastoral fire data

```{r}
clean_names(pasto_fire)->pasto_fire
pasto_fire%>%
  select(annee:source)->pasto_fire

pasto_fire%>% 
  slice(c(1:61,64:76,78:817,819:821,823:945,947:nrow(pasto_fire)))-> pasto_fire

pasto_fire%>%
  mutate(annee=as.integer(annee),
         mois=as.integer(mois),
         jour=as.integer(jour),
         code_commune=as.character(code_commune),
         commune=as.character(commune),
         surface_ha=as.numeric(surface_ha),
         type_vegetation=as.factor(type_vegetation),
         source=as.factor(source))->pasto_fire

# pasto_fire%>%
#   filter(surface_ha=="na")%>%
#   count->na1
# test%>%
#   filter(is.na(surface_ha))%>%
#   count->na2
# na1==na2
# 
# seqna1<-which(pasto_fire$surface_ha=="na")
# seqna2<-which(is.na(test$surface_ha))
# tabcomp<-cbind(seqna1,seqna2)
# tabcomp<-as_tibble(tabcomp)
# tabcomp%>%
#   mutate(diff=(seqna1-seqna2))->tabcomp
# tabcomp%>%
#   filter(diff!=0)

#370,1397,3225

pasto_fire%>% 
  mutate(date = make_datetime(annee, mois, jour))->pasto_fire
```

-   Commune GPS data

```{r}
commune_gps%>%
  mutate(code_insee=as.character(code_insee),
         longitude=as.numeric(longitude))%>%
  na.omit(longitude)%>%
  distinct(code_insee,.keep_all=T)->commune_gps
```

3.  Data merging

```{r}
fire_mix<-bind_rows("agri_fire"=agri_fire,"pasto_fire"=pasto_fire,.id="groups")
fire<-left_join(fire_mix,commune_gps,by=c("code_commune"="code_insee"))
fire%>%
  na.omit(latitude)->fire
```

4.  Creating other format files

```{r}
fire_sf<-st_as_sf(fire,
               coords = c("longitude","latitude"),
               crs="+proj=longlat +datum=WGS84 +nodefs")
```

# Data exploration

```{r}
agri_fire%>%
  group_by(mois,jour)%>%
  count%>%
  mutate(mois=as.factor(mois))%>%
  ggplot()+
  aes(x = jour,y=n,color=mois)+
  geom_line()
agri_fire%>%
  group_by(date)%>%
  count%>%
  ggplot()+
  aes(x=date,y=n)+
  geom_line()
agri_fire%>%
  group_by(code_commune)%>%
  count%>%
  arrange(desc(n))%>%
  ggplot()+
  aes(x = code_commune,y=n)+
  geom_line()
```

2.  Spatial exploration

```{r}
tmap_mode("view")
fire_sf%>%
  filter(groups=="agri_fire")%>%
tm_shape()+
  tm_dots(size="surface_ha",col="surface_ha",palette=c('#ffffcc','#ffeda0','#fed976','#feb24c','#fd8d3c','#fc4e2a','#e31a1c','#b10026'),
          title="Burned area (ha)",alpha=0.8,n=8,scale=2)->BA_agri_bubble
print(BA_agri_bubble)
tm_shape(fire_sf)+
  tm_bubbles(size = "surface_ha",col = "red",scale = 1)

tmap_mode("plot")
osm_fire_sf<-read_osm(fire_sf,ext=1.1)
tm_shape(osm_fire_sf)+
  tm_rgb()+
tm_shape(fire_sf)+
tm_tiles("OpenStreetMap")+
    tm_dots(col="groups",
          title="Burned area (ha)",
          palette=c("#2ca25f","#2b8cbe"),
          alpha=0.8,
          n=8,
          scale=2,
          legend.show =F 
          )+
  tm_facets(by="groups",free.coords = F)+
	tm_layout(panel.labels = c("Agricultural fire events", "Pastoral fire events"))->BA_Facet
print(BA_Facet)
```

# Export data

```{r}
tmap_save(BA_agri_bubble, filename = "output_data/BA_agri_bubble.html")
tmap_save(BA_Facet, filename = "output_data/BA_facet_facet.png")
```
